[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@eth-infinitism/account-abstraction=lib/account-abstraction/contracts", 
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", 
    "@cyfrin/foundry-devops=lib/foundry-devops/src",
    "@cyfrin/foundry-era-contracts=lib/foundry-era-contracts/src"
]
fs_permissions = [{access = "read-write",path = "./broadcast"}]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
s_system = true #, need to --system-mode=true
via-ir = true

[fmt]
line_length = 120
format_on_save = true
